### ISSUE TITLE
Leadás előtt feladatok

### ISSUE THREAD

**Issue by gknyihar** [OnionKiller/BigDataAssignment-2022#5]
- [ ] Hipotézisek beleírása
- [x] Korrelációs mátrix nagyítás
- [x] Statikus oldal?
- [x] Ábrák feliratozása és tisztázása
- [x] Telepítési útmutató tesztelése, conda alternatíva?
- [x] EDA kicsit átrendez, ami jobban mutatja a logikai menetet (előbb a glob adat)

**Comment by OnionKiller** [comment]
Hipotéziseket nem fogalmaztam annyira meg, ahhoz mennyire ragaszkodunk?

**Comment by gknyihar** [comment]
Szerintem nem fontos
